### ISSUE TITLE
noncollinear WF components written to wrong filenames

### ISSUE THREAD

**Issue by bernstei** [kylebystrom/pawpyseed#13]
`NCLWavefunction` writes its components with 
```python
		filename1 = "%s_UP_REAL" % filename_base
		filename2 = "%s_DOWN_REAL" % filename_base
		filename3 = "%s_UP_IMAG" % filename_base
		filename4 = "%s_DOWN_IMAG" % filename_base
		res0, res1 = self._write_realspace_state(filename1, filename2, filename3, filename4,
											scale, b, k, s)
```
but from what I can tell from the pawpyc.pyx, filenames 1 & 2 should correspond to real and imaginary parts (referred to as `resr` and `resi`), and 3 & 4 to real and imaginary parts, respectively, so these files are being misnamed.  This is in pawpyc.pyx around line 600, in the definition of 
```python
	def _write_realspace_state(self, filename1, filename2, filename3, filename4,
								double scale, int b, int k, int s):
```

**Comment by kylebystrom** [comment]
Sorry for the late reply. Thanks for catching this and #12. I will push fixes today.

**Comment by kylebystrom** [comment]
Should be fixed now. File names are in the right order and self.dim gets passed instead of dim. Let me know if it works, and if so I can close these.

**Comment by bernstei** [comment]
Thanks - the new code looks good.  I did just notice that `NCLWavefunction.write_density_realspace()` (which I don't use, and therefore haven't tested) appears to need the same `dim` -> `self.dim` fix when it calls `_convert_to_vasp_volumetric()`.

**Comment by kylebystrom** [comment]
You're right. I just fixed that too. Thanks for again for catching these bugs! The changes are on master right now; I will probably add a new version to PyPI in a couple weeks after a few other small additions I am planning.

**Comment by bernstei** [comment]
Not really reopening, but do you know when you're planning to update the PyPI version?  It's still showing a June 2020 release.

**Comment by kylebystrom** [comment]
Just updated PyPI (v0.6.4). Thanks for the reminder!
